<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Abhay" failures="1" tests="9" name="com.PlanIT.WitsLab.tests.BacklogTestScript" time="1114.077" errors="0" timestamp="04 Dec 2023 09:12:38 GMT" skipped="0">
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCloneIssueFunctionality" time="163.974">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.PlanIT.WitsLab.tests.BacklogTestScript.verifyCloneIssueFunctionality(BacklogTestScript.java:418)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCloneIssueFunctionality -->
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="moveTicketFromOneBoardToAnother" time="180.650"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCreateSprintFunctionality" time="63.657"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyAddMemberFunctionalityFromBoard" time="139.184"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCreateIssueFromBoard" time="115.189"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyCreateIssueFromBacklogFunctionality" time="107.911"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifySprintActivation" time="69.780"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyExistingProjectMemberFunctionalityToBoard" time="73.895"/>
  <testcase classname="com.PlanIT.WitsLab.tests.BacklogTestScript" name="verifyMoveAllIssueFromBacklogToSprint" time="199.837"/>
</testsuite> <!-- com.PlanIT.WitsLab.tests.BacklogTestScript -->
